### ISSUE TITLE
print_integer throws Exception: Instruction JSR not implemented for anything beside print (FFD2)

### ISSUE THREAD

**Issue by arne-cl** [fotcorn/Python-C64-Emulator#2]
running `python main.py  examples/print_integer` returns this error:

``` python
./main.py  examples/print_integer
Traceback (most recent call last):
  File "./main.py", line 24, in <module>
    cpu.run(0xC000)
  File "/home/arme/bin/Python-C64-Emulator/cpu.py", line 53, in run
    self.execute(instr)
  File "/home/arme/bin/Python-C64-Emulator/cpu.py", line 143, in execute
    raise Exception('Instruction JSR not implemented for anything beside print (FFD2)')
Exception: Instruction JSR not implemented for anything beside print (FFD2)
```

**Comment by fotcorn** [comment]
As the comment in the source of the example says, the emulator misses implementation of the JSR and RTS instructions: https://github.com/fotcorn/Python-C64-Emulator/blob/master/examples/print_integer.asm#L1

To make these two work, we need a working stack first. Pull requests welcome ;)
